{
    "recursionBound": 8,
    "k": 1,
    "main": "CorralEntry_ArrayLength",
    "expectedResult": "Verifying program while tracking: {assertsPassed}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, a_ArrayLength, Length}
Program has a potential bug: False bug
Verifying program while tracking: {assertsPassed, a_ArrayLength, Length, Alloc, M_int_int}
Program has a potential bug: True bug
PersistentProgram(122,1): error PF5001: This assertion can fail

__SolToBoogieTest_out.bpl(80,1): error PF5001: This assertion can fail"
}
